
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
require("dotenv/config");
const { defineConfig, env } = require("prisma/config");

module.exports = defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "binary", // NOT classic
  datasource: {
    url: env("DATABASE_URL"),
  },
});
